replicaCount: 1

deploymentConfig:
  terminationGracePeriod: 60
  containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

image:
  repository: dsdatsme/key-server-flask
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: []
nameOverride: "key-server-app"
fullnameOverride: "key-server-app-deployment"

serviceAccount:
  create: true
  name: "key-server-app-sa"

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-issuer
  hosts:
    - host: dsdatsme.ddns.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dsdatsme.ddns.net
      secretName: dsdatsme-cert

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
