controller:
  ingressClass: publicingress
  use-forwarded-headers: "true"

  ingressClassResource:
    enabled: true
    default: false

  publishService:
    enabled: true
 
  kind: Deployment
  terminationGracePeriodSeconds: 300

  replicaCount: 1
  minAvailable: 1
  resources:
    limits:
     cpu: 300m
     memory: 300Mi
    requests:
      cpu: 100m
      memory: 90Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  service:
    enabled: true

    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: LoadBalancer

    internal:
      enabled: false

    externalTrafficPolicy: Local

  admissionWebhooks:
    enabled: true

  metrics:
    enabled: false


defaultBackend:
  enabled: true
  replicaCount: 1
  minAvailable: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  resources:
    requests:
      cpu: 30m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50


podSecurityPolicy:
  enabled: true
